### ISSUE TITLE
Report abt harrasment by @Blu_eibell

### ISSUE THREAD

**Issue by Ritzz87** [MasterGroosha/telegram-report-bot#10]
Harasser's username: @Blu_eibell
Date/Time: Around 7 pm, November 9, 2024
Description: [Harasser] sent unsolicited explicit photos and messages, attempting to engage in sexting. I denied and asked them to stop.

Attachments: I added screenshots or evidence

Relationship: on telegram chat. 

[images removed]

**Comment by MasterGroosha** [comment]
Please report all the content within Telegram using "Report" button. My bot serves completely different purpose.
